// Auto-generated by tools/sync-provider-catalogs.mjs
// Source: https://developers.openai.com/api/reference/resources/audio/subresources/speech/methods/create

export const openAIKnownVoices = [
  'alloy',
  'ash',
  'ballad',
  'coral',
  'echo',
  'fable',
  'onyx',
  'nova',
  'sage',
  'shimmer',
  'verse',
  'marin',
  'cedar',
] as const;
